# Generated by Django 3.1.1 on 2022-12-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Trainno', models.IntegerField(help_text='Trainno', primary_key=True, serialize=False)),
                ('Passengername', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Noofseat', models.IntegerField()),
            ],
        ),
    ]
